### ISSUE TITLE
Vinelab\Bowler\Exceptions\Handler::__construct() Invalid Argument

### ISSUE THREAD

**Issue by TheOneDaveYoung** [Vinelab/bowler#29]
Just installed via Composer and using artisan commands as described in the README but running into the following error when executing php artisan bowler:consume {queue_name}

`Argument 1 passed to Vinelab\Bowler\Exceptions\Handler::__construct() must implement interface Vinelab\Bowler\Contracts\BowlerExceptionHandler, inst
  ance of App\Exceptions\Handler given`

Kind of stuck here!

My app is on a pretty standard Laravel 5.6.33 setup.

**Comment by harris21** [comment]
Hey @TheOneDaveYoung , do you implement `BowlerExceptionHandler` in you `Exceptions/Handler.php` file? There is a step in the docs near the bottom where this is mentioned.

**Comment by TheOneDaveYoung** [comment]
I did not. It's pretty hard to find in the doc considering adding the "implements" to the app/Exceptions/Handler class breaks things. :-)

Thanks for the quick response!
