### ISSUE TITLE
ErrorException  : Undefined index: driver

### ISSUE THREAD

**Issue by LauerPaul** [Vinelab/bowler#38]
I can not run `php artisan queue:work`

**Comment by harris21** [comment]
Hey @LauerPaul , did you try to run `php artisan bowler:consume queue-name-here` ?

**Comment by harris21** [comment]
@LauerPaul 
Please add to your `Exceptions/Handler.php` the `implements BowlerExceptionHandler` like it is being mentioned in the docs https://github.com/Vinelab/bowler#error-reporting and implement the following function in the same file: `reportQueue(Exception $e, AMQPMessage $msg)`.
Let me know if this worked for you.

**Comment by LauerPaul** [comment]
Thanks for the help, added the line
```
use PhpAmqpLib\Message\AMQPMessage;
use Vinelab\Bowler\Contracts\BowlerExceptionHandler;
```
edit `class Handler extends ExceptionHandler implements BowlerExceptionHandler`
and it all worked!

**Comment by harris21** [comment]
Cheers!
