### ISSUE TITLE
bowler:consume

### ISSUE THREAD

**Issue by snezhkoigor** [Vinelab/bowler#41]
Hi. Can I consume multi queues?

For example like in Laravel php artisan queue:work hight,middle,low ?

**Comment by KinaneD** [comment]
Hello @snezhkoigor, you cannot atm, since each `consume` command is a standalone run loop. For now, Bowler is single threaded.

**Comment by snezhkoigor** [comment]
@KinaneD 

Thanks. So I need run php artisan bowler:consume hight, php artisan bowler:consume middle, php artisan bowler:consume low in different tab for example? Or you have best solution?

**Comment by KinaneD** [comment]
Yes, that the way to go for now.
Cheers.

**Comment by snezhkoigor** [comment]
@KinaneD

Thanks
