### ISSUE TITLE
php-amqplib/php-amqplib

### ISSUE THREAD

**Issue by snezhkoigor** [Vinelab/bowler#43]
Hi.

Why are you using v2.6.1?

**Comment by KinaneD** [comment]
No specific reason, that was the latest version when this package was created. We are interested in a version bump too, we didn't get the chance to work on that yet.

**Comment by snezhkoigor** [comment]
In your plans? :)

**Comment by KinaneD** [comment]
Sure, If you check the branches in your fork there is one called `update/amqplib` we didn't get the chance to work on that. We cannot commit to a delivery date at the moment, but it is definitely something we are looking forward to.

**Comment by KinaneD** [comment]
Released https://github.com/Vinelab/bowler/releases/tag/v0.4.4
