### ISSUE TITLE
bowler:consume

### ISSUE THREAD

**Issue by snezhkoigor** [Vinelab/bowler#45]
Hi :)

One more time :) Do you think that this package must has feature for run consumers by this syntax

php artisan bowler:consume queue_1,queue_2,...queue_n

Or this is bad practice?

**Comment by KinaneD** [comment]
Hello, programmatically it is possible, but due to the complexity of managing concurrent processes in php we won't be getting into this anytime soon.

**Comment by snezhkoigor** [comment]
@KinaneD 

I understand. Thanks.
