### ISSUE TITLE
Use of undefined constant SOCKET_EAGAIN - assumed 'SOCKET_EAGAIN'

### ISSUE THREAD

**Issue by snezhkoigor** [Vinelab/bowler#47]
Hi!

Use of undefined constant SOCKET_EAGAIN - assumed 'SOCKET_EAGAIN' (this will throw an Error in a future version of PHP)

How to fix this?

**Comment by KinaneD** [comment]
Hi,
What is the issue, when does it occur, which version are you using, what were your research findings, ...

Please provide details so that we can help you.

**Comment by snezhkoigor** [comment]
Sorry.

v0.4.4
php 7.2

I saw that this error display without php sockets ext. but I've enabled this ext and no result.

This is error from php-amqp v2.8.* (in v2.6 no this type error)

**Comment by KinaneD** [comment]
Hello @snezhkoigor,
We are running v0.4.4 on production without any issues.

True it seems to be an php-amqp library issue.
When do you get this error?

**Comment by snezhkoigor** [comment]
Hi @KinaneD 

When I'm trying to publish some message ... maybe I've missed some php ext?

**Comment by KinaneD** [comment]
Nothing that i am aware of.
Where you able to solve this?
